apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app         #name for this deployment 
spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-app

  template:               #how to create a pod 
    metadata:
      labels:
        app: flask-app

    spec:             #pod specs
      containers:     #containers to run inside the pod
        - name: flask-app
          image: haroonashar/flask-app:61
          ports:
            - containerPort: 5000