apiVersion: v1
kind: Service
metadata:
  name: flask-service

spec:
  type: NodePort    #port exposed on kubernetes node so service is reachable throught that port

  selector:     #select the pods to send traffic to 
    app: flask-app

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007 